### ISSUE TITLE
Rolls not working

### ISSUE THREAD

**Issue by ehwhattaugonnado** [jbhaywood/foundryvtt-honeyheist#1]
Foundry 0.7.8
For some reason only the rolls with advantage are working in the actor sheet. Rolling bear or criminal with a single die or trying to roll an attribute does nothing.

Rolls that are failing don't seem to generate anything in the logs.

**Comment by jbhaywood** [comment]
I'll look into that. Thanks for pointing it out.

**Comment by jbhaywood** [comment]
I've uploaded a fix and packaged up a new version, but I can't access the admin site to update it officially on the Foundry site. I'm waiting on support to fix that, but if you want to download the new version before then, you can do that here: https://github.com/jbhaywood/foundryvtt-honeyheist/archive/v1.1.zip
