### ISSUE TITLE
Link to 1.3 installs 1.23

### ISSUE THREAD

**Issue by adamglinder** [jbhaywood/foundryvtt-honeyheist#11]
Using the manifest URL to install v1.3 installs v1.23 instead. Shows compatibility risk with Foundry v10.

**Comment by jbhaywood** [comment]
Which manifest url do you mean? It installs fine from Foundry itself as far as I can tell and I don't see any compatibility risk warnings.

**Comment by adamglinder** [comment]
Seemed to be a Forge issue, sorted it out. The game system works perfectly.
