### ISSUE TITLE
Version 1.3 seems to be newer than version 1.24

### ISSUE THREAD

**Issue by SiCoe** [jbhaywood/foundryvtt-honeyheist#12]
The [available versions on the foundryvtt website](https://foundryvtt.com/packages/honey-heist/) show the order of the versions, there is a big jump between version 1.**3** and version 1.**21**.

![image](https://github.com/jbhaywood/foundryvtt-honeyheist/assets/1493839/e4744bd0-a074-412f-bebb-45daaa32173d)

I suspect what was intended was for version 1.21 and 1.24 to really be 1.2.1 and 1.2.4 respectively.

I only highlight this as it confused me as to what was the latest version. It also shows version 1.21 when searching for it within FVTT itself:

![image](https://github.com/jbhaywood/foundryvtt-honeyheist/assets/1493839/c737a336-a26a-40c4-bab5-f81e9b01cfa7)

**Comment by jbhaywood** [comment]
It shows as 1.3 for me...
![image](https://github.com/jbhaywood/foundryvtt-honeyheist/assets/5131886/2ef690f0-c0ea-4a7c-be4c-d61f35966ae4)

I don't know why it lists them out of order on the Foundry website. The whole way it does module versioning is messed up, in my opinion. You can see here that the last one I added was 1.3...
![image](https://github.com/jbhaywood/foundryvtt-honeyheist/assets/5131886/f6b1026d-dd23-415e-bacd-b9da538776ca)

And you can see on the GitHub repository that it's the latest version. That only thing I can think of is that you're still on v9 or earlier of Foundry, in which case you wouldn't be able to use 1.3 of the Honey Heist system.

**Comment by SiCoe** [comment]
I'm on v11 in Foundry so they might have changed it from v10

**Comment by jbhaywood** [comment]
If this is an issue with v11 only then I don't really have any interest in updating it. This is a super simple system and shouldn't need any maintenance. Tbh, I'm kind of tired of Foundry's philosophy that it's ok to break things every release and then leave it up to us unpaid volunteers to clean up after their changes. I'll leave this open though to see if someone else wants to take on the work of updating it.

**Comment by SiCoe** [comment]
Understandable. I may have a look myself if I get the time.

**Comment by Geekswordsman** [comment]
It's because you have to look at each part of the version separately and compare, so comparing 1.3 and 1.24 you get...
1 === 1
24 > 3

I ran into this problem as well.  I think 24 and the like was _meant_ to be 1.2.4, rather than 1.24.

So the only way to get past this is either do v2 and start fresh or start using major/mino to match 24 (so this would mean 1.3 is 1.30)

**Comment by jbhaywood** [comment]
Made some change. Maybe that fixed it?
