### ISSUE TITLE
Upgrade to v12

### ISSUE THREAD

**Issue by Cussa** [jbhaywood/foundryvtt-honeyheist#15]
Is there any plan to update the system to the Foundry v12?

**Comment by jbhaywood** [comment]
It's been a while since I touched this system and I haven't looked into what's involved with updating. If someone out there in the internet void wants to take it on and do a pull request I'm all for it. I'm guessing there's not a lot to it, if you already know what's needed.

**Comment by jbhaywood** [comment]
Updated thanks to a kind internet stranger.
