### ISSUE TITLE
Issue moving points manually between Bear and Criminal

### ISSUE THREAD

**Issue by corpocracy** [jbhaywood/foundryvtt-honeyheist#7]
I was testing out the system and I'm getting strange issues with the manual move point buttons. At first they worked okay, but when a bear maxed out on a stat (say 6 on criminal) and I tried to move a stat back manually, it would delete 1 point from one side, but wouldn't  add to the other (getting scores of 0 and 5, then 0 and 4, and so on). Then, occasionally, it would work as intended, but now I have fewer stats to work with overall (so I would get a score of 1 and 1, etc.).

I then tried to recreate the issue by creating a brand new actor and trying it again. But now I'm getting a stranger issue. As an example, when I start out with a fresh actor and try to move stats to Bear, a point gets deleted from Bear and all points gets deleted from Criminal (so scores go from 3 and 3 to 2 and 0). And now it keeps happening with each new actor I make.

I don't see any console log errors and I'm having a rough time recreating what caused this in the first place. The only mod I have on is DSN. Please let me know if you need any more info on this.

Edit: One final note. I don't think this would be a huge issue, except I can't seem to figure out how to reset the stats on the actor or manually change them. As is, the only solution I see is deleting the actor and creating a new one, and even then, the buttons seemed to be bugged out for me now.

![image](https://user-images.githubusercontent.com/62632755/144171843-d47e2325-43d4-4439-b68c-a92179e43717.png)

**Comment by jbhaywood** [comment]
That's really strange. I don't know what would be interfering with the numbers like that, and I'm not seeing it happen on my end. Is the Honey Heist system up to date? And which version of Foundry are you using?

**Comment by corpocracy** [comment]
I will double check when I get home, but I believe the system is up to date (I just downloaded it a few days ago). It's a fresh install and I haven't really done anything with it yet. I'm playing on 8.9 foundry. One other wrinkle is I was hosting through Forge (not sure if that would make a difference). It was definitely strange and kept changing. Sometimes hitting the button would work as expected, sometimes it didn't. If you like me to try and export the world/actors I can and/or I can invite you into my world to see.

**Comment by jbhaywood** [comment]
I don't see how Forge, or anything really, would be affecting those stat calculations. It's just math. I'm looking at the code and don't see how it could adjust only one of the two numbers. It always operates on both stats together.

Maybe exporting would help. I really need to see it in action with a local repro to figure out what's going on. The only thing I can think of is that it's not getting the correct value from the html element of the character sheet. I wonder if deleting and reinstalling the system would help, if maybe some file is corrupt in some way and needs to be restored.

Actually, can you zip up the system folder and attach it here? That might help. It'll be the Foundry...\Data\systems\honey-heist folder.

**Comment by corpocracy** [comment]
Hmmm, Forge doesn't give me an option to export the actual systems folder. It does give me the option to zip up the world folder if that helps:
[ForgeVTT-export-honey-test-2021-12-02_5_46_49.zip](https://github.com/jbhaywood/foundryvtt-honeyheist/files/7639333/ForgeVTT-export-honey-test-2021-12-02_5_46_49.zip)

If you check out the actors, you can see some of the issues that I've been having (just from clicking back and forth between Bear and Criminal). I can try deleting and reinstalling next if you think that might help!

**Comment by corpocracy** [comment]
Alright, I tried to recreate it with the local Foundry App with a fresh install of the system with a freshly created world and I was able to re-create the issue. I still haven't pinpointed the root cause, but just by playing around with the transfer buttons (clicking them back and forth), the numbers eventually started getting wonky again, either transferring multiple points at a time, transferring negative points, or adding points but not actually subtracting them from the other side. Since this was on my local computer, I was able to zip both the system folder and the world folder this time:
[honey-heist.zip](https://github.com/jbhaywood/foundryvtt-honeyheist/files/7639502/honey-heist.zip)
[honey-test.zip](https://github.com/jbhaywood/foundryvtt-honeyheist/files/7639504/honey-test.zip)

**Comment by jbhaywood** [comment]
Wow, there's something really weird going on with the world. I'm looking at the numbers on the screen in the character sheet, verifying them with the browser debug tools, but getting different numbers when they're queried with javascript. I don't even know how that's possible. I'll need to investigate more. This is a head scratcher for sure.

Oh wait, if you have two character sheets open at the same time, it's pulling the numbers from the first one that was opened, not the one being clicked on. If there's only one open at a time, it works fine. I guess it never came up because most people would only have their one character open at a time. Ok, I'll have to look into what I'm doing wrong.

EDIT
This is still not exactly what you were describing, and it's not specific to your world. I reproed with my own world too. But it's something that's not right, so maybe fixing this will fix the other issues you were seeing.

**Comment by jbhaywood** [comment]
Ok, it should be fixed now in version 1.24. There were definitely problems with how the code was written. You should make new characters after updating, especially for the ones whose numbers don't make sense, like 1 and 1.

**Comment by corpocracy** [comment]
Ohhhhh... That makes sense! I did typically have multiple sheets open. As the GM I often have the sheets open for multiple actors to keep track of stuff. Awesome! Thanks for looking into this! I look forward to running a game soon!
